spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/studentmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "09140727"
    driver-class-name: com.mysql.jdbc.Driver
    mvc:
      favicon:
        enabled: false
    thymeleaf:
      mode: HTML
      encoding: utf-8
      cache: false
      prefix: classpath:/templates/

